---
title: "Compare Business Dynamism Across the 50 States"
output: 
  flexdashboard::flex_dashboard:
    theme: spacelab
    orientation: rows
    source_code: embed
    vertical_layout: scroll
runtime: shiny
---

```{r setup, include=FALSE}
library(shiny)
library(flexdashboard)
library(ggplot2)
library(DT)
library(stringr)
library(dplyr)
library(tools)
library(plotly)

# Load file
busdyn <- read.csv(file = "BDS_Data_04_18.csv", fileEncoding="UTF-8-BOM")

# Remove Underscores in Column and Row Names
gsub(x = names(busdyn), pattern = "_", replacement = " ") 

```
Inputs {.sidebar}
-----------------------------------------------------------------------
```{r sidebar}
# User selects which state(s) to graph------------------------------------------
checkboxGroupInput("state", "State(s)", choices = unique(busdyn$State),
                  selected = "Alabama", inline = TRUE
                  )

# User selects which year(s) to graph-------------------------------------------
sliderInput("year", "Year(s)",
            min = (2004), max = (2018),
            value = c(2004,2018), sep = ""
            )

# User selects type of chart to plot---------------------------------------------
radioButtons("plot_type", "Choose plot type showing job reallocation across all states", 
             choices = c("Box plot", "Violin Plot"), selected = c("Box plot"))
```
Outputs
Column {data-width=650}
-----------------------------------------------------------------------

### Chart 1: Rate of Establishments

```{r plots}
# Create subset of dataset based on user year and state inputs showing new estabs
busdyn_subset <- reactive({
  req(input$state, input$year) #ensure user has chosen what to graph
  subset (busdyn, State == input$state & Year == input$year, select = c(State, Year, Rate_of_establishments_born_prev_year, Rate_of_jobs_created_from_opening_establishments_prev_year))
})

# Create histogram of data subset
renderPlot({
ggplotly(ggplot(busdyn_subset(), aes(x = State, y = Rate_of_establishments_born_prev_year)) +
  geom_bar(stat = "identity", width = .4) +
  labs(y = "Rate of Establishments Born in the Previous Year",
       x = "State",
       title ="The Best Performing States on Business Creation (Subsetted Data)",
       subtitle = "Share of all firms that are 1 year old or younger",
       caption ="Source: U.S. Census Business Dynamics Statistics Survey"),
         tooltip = c("x", "y")
)
})

# Create scatterplot of data subset
renderPlot({
ggplotly(ggplot(busdyn_subset(), aes(x = Rate_of_establishments_born_prev_year,
                            y = Rate_of_jobs_created_from_opening_establishments_prev_year)) + 
         geom_point(aes(col = State)) +
         labs(y = "Rate of Jobs Created from New Establishments",
              x = "Rate of Establishments Born Previous Year",
              title = "The Best Performing States on Business Creation and Resultant Jobs (Subsetted Data)",
              subtitle = "Share of all firms that are 1 year old or younger and share of jobs at these firms", 
              caption = "Source: U.S. Census Business Dynamics Statistics Survey"),
         tooltip = c("x", "y")
)
})

#Create boxplot or histogram of all data
renderPlot({
  if(input$plot_type == "Box Plot"){
    ggplotly(ggplot(busdyn, aes(x = Year, y = Rate_of_reallocation_prev_year)) +
               geom_boxplot()+
               labs(y = "Rate of Job Reallocation Previous Year",
                    x =  "Year",
                    title = "The Distribution of Job Reallocation Rates across the States, 2004-2018",
                    subtitle = "Sum of jobs created and destroyed - measuring how quickly jobs more from shrinking to expanding firms",
                    caption = "Source: U.S. Census Business Dynamics Statistics Survey")
          )}
    
  else {
    ggplotly(ggplot(busdyn, aes(x = Year, y = Rate_of_reallocation_prev_year)) +
      geom_violin()+
      labs(y = "Rate of Job Reallocation Previous Year",
           x =  "Year",
           title = "The Distribution of Job Reallocation Rates across the States, 2004-2018",
           subtitle = "Sum of jobs created and destroyed - measuring how quickly jobs more from shrinking to expanding firms",
           caption = "Source: U.S. Census Business Dynamics Statistics Survey"))
}
})
```

Column {data-width=350}
-----------------------------------------------------------------------

### Value Boxes

```{r valueboxmean}
# Value Box showing average value of Rate_of_establishments_born_prev_year
renderValueBox({
valueBox(value = (mean(busdyn_subset()$Rate_of_establishments_born_prev_year)), "Average Annual Rate of Business Creation", icon = NULL)   })

```

```{r valueboxmax}
# Value Box showing average value of second metric graphed
renderValueBox({
valueBox(value = (max(busdyn_subset()$Rate_of_establishments_born_prev_year)), "Max. Annual Rate of Business Creation", icon = NULL) 
  })

```

```{r valueboxmin}
renderValueBox({
valueBox(value = (min(busdyn_subset()$Rate_of_establishments_born_prev_year)), "Min. Annual Rate of Business Creation", icon = NULL) 
  })
```

### Data Table

```{r datatable}
# Data Table corresponding to scatterplot
reactive({DT::datatable(busdyn_subset(), 
          class = "cell-border stripe",
          caption = "Table of user-subsetted data",
          )
})
```

```{r context="render"}
plotOutput("weight_plot")
```